### ISSUE TITLE
Server-client example for <asyncio API>

### ISSUE THREAD

**Issue by etkaar** [aiortc/aioquic#191]
Is there any server<->client example with multiple concurrent client connections available for the asyncio API?
https://aioquic.readthedocs.io/en/latest/asyncio.html

**Comment by possessedbysatan** [comment]
What do you mean _server-client_? http3-server.py already can already manage multiple connections since it creates an instance of QuicConnectionProtocol for each client

**Comment by etkaar** [comment]
Sorry, I did mean _server<->client_.

> What do you mean by _server-client_? http3-server.py already can already manage multiple connections since it creates an instance of QuicConnectionProtocol for each client

There is an QUIC API, HTTP/3 API and asyncio API but for the latter there is no example unfortunately.

**Comment by possessedbysatan** [comment]
> Sorry, I did mean _server<->client_.
> 
> > What do you mean by _server-client_? http3-server.py already can already manage multiple connections since it creates an instance of QuicConnectionProtocol for each client
> 
> There is an QUIC API, HTTP/3 API and asyncio API but for the latter there is no example unfortunately.

I think you need to elaborate further since the examples already allow bidirectional _server<->client_ communication. However, if the thing you want is something that can act as both a server and a client (i.e. it can accept connections but it also can start connections towards remote peers) things get more complicated. Is this what you're looking for? I could help you.

**Comment by etkaar** [comment]
No, I was only looking for a asyncio API server<->client multiplexing example, where the server never changes its role as server and is able to serve n clients concurrently 😊

Thanks for your help! But please don't invest too much effort if there is no easy example for this (alternatively one could add the example than to `aiortc/aioquic/tree/main/examples`), because unfortuantely in the meantime, I am not sure if I still can use QUIC because I would be required to ensure compatibility with PHP and I didn't find a PHP library for it.

**Comment by possessedbysatan** [comment]
Oh, I think I kinda got your point. I guess you want a real-world example where usually a client will request quite a lot of resources using multiple streams. If that's the case, then you can:

1. Make a bunch of `H3Connection.send_headers(stream_id=get_next_available_stream_id()...)` calls and store identifiers to such calls somewhere, maybe in a dict so that you can know later if said request was served or not. This way you effectively make a bunch of concurrent request using multiple QUIC streams.

2. In the server, you'd need to watch out for HTTP/3 `HeadersReceived` events, and then serve your requests using the same stream_id that was used to request them. You send the client the necessary headers (`:status`, `:method`, etc...) with `H3Connection.send_headers()` and if you determine the request is somehow correct you then send data using `H3Connection.send_data(data=..., end_stream=True)`. 

There's Hypercorn (web app server) which internally uses aioquic to provide QUIC support (you don't have to worry about multiplexing and all that stuff) but it's python-only.

**Comment by fareedlb** [comment]
> > Sorry, I did mean _server<->client_.
> > > What do you mean by _server-client_? http3-server.py already can already manage multiple connections since it creates an instance of QuicConnectionProtocol for each client
> > 
> > 
> > There is an QUIC API, HTTP/3 API and asyncio API but for the latter there is no example unfortunately.
> 
> I think you need to elaborate further since the examples already allow bidirectional _server<->client_ communication. However, if the thing you want is something that can act as both a server and a client (i.e. it can accept connections but it also can start connections towards remote peers) things get more complicated. Is this what you're looking for? I could help you.

@rakbladsvalsen Hello, I just came across this thread and was wondering if you have any pointers on how to implement this. For example,  seller and multiple buyers (all autonomous) exchanging messages (over QUIC but not HTTP/3). Many thanks.
