### ISSUE TITLE
Sender backpressure?

### ISSUE THREAD

**Issue by rthalley** [aiortc/aioquic#328]
Caveat: I looked for this in the issues and didn't see it; if I missed it I apologize.

Imagine I have an aioquic server and a client asks me to send something absolutely huge.  As far as I can tell, as fast as my server can call send_stream_data(), I'll extended the _buffer bytearray in the stream's sender.  Aioquic will deal with congestion sending to the client, but there's nothing to stop me from buffering excessive amounts of memory in the buffer and getting killed by the operating system's out-of-memory mechanism.  I'd like a way to have backpressure on the sender.  E.g. have whatever write() method I have that's calling into aioquic know if "too much" is buffered in aioquic, and if so block the thread/coroutine until the buffer is smaller or empty.  But I don't see any way to manage knowing when to block, and more importantly, when to wake up.

Have I missed something?  If I haven't, then a mechanism that preserves the separation between the Quic machine and I/O would be returning a "hey, you are over the limit" indication from send_stream_data(), and calling a callback when it goes below the limit.  I picked a callback here as we don't want the blocked thread to poll, as that introduces latency in it waking up and/or wastes effort polling when progress is still not possible.  I considered returning an event too, but that had the same latency issue due to event processing being associated with timers or the send thread typically.  Of course, there might be other mechanisms!  This is just what I've thought of so far.

So maybe we have:

def send_stream_data(self, stream_id: int, data: bytes, end_stream: bool = False,
                                       ok_to_send: Callable[[int], None] | None = None) -> bool

where the the function returns True if not over the limit, and False if over.  The parameter to the callback is the stream_id.
There would also need to be functions to get and set the blocking limit on the stream.

I just extended send_stream_data() as it seemed pretty backwards compatible given the ok_to_send callback is optional and defaults to None, and the prior return value was None, but I'm happy enough if you wanted a separate method for this.

Thoughts?

**Comment by rthalley** [comment]
After slightly more thought, probably the return value should be an int, which is how much of data got copied into the buffer.  Then if < len(data) I know to block, and I know how much got copied.  This makes things simpler than the boolean scheme as you can have an absolute buffer size limit in the stream sender.

**Comment by rthalley** [comment]
There's a similar issue for reader backpressure too, in that if I have a bunch of streams but one of them is not reading input for a long time, I want some way to get aioquic to stop emitting events for that stream until I say it is ok, buffer the data it got, and initiate flow control to the other end if the buffer for the stream gets too big.

**Comment by gschaffner** [comment]
>There's a similar issue for reader backpressure too, in that if I have a bunch of streams but one of them is not reading input for a long time, I want some way to get aioquic to stop emitting events for that stream until I say it is ok, buffer the data it got, and initiate flow control to the other end if the buffer for the stream gets too big.

I was just taking a look at the code here because we are considering using aioquic in a RPC library and I did not understand how aioquic's APIs got the information required from the application to do flow control. I confirmed that the issue seems to still be present on main (34c5eac106a39bdb1ac91c8d742b047a409bd189): `MAX_STREAM_DATA` gets sent automatically by `_write_stream_limits` when data is received by the state machine (but not yet by the application code), so stream receivers cannot apply backpressure or limit their buffering. #589 is related.

In terms of API design for informing the state machine when the application is ready to send `MAX_STREAM_DATA` to unblock a sender, copying h2's API design might make sense here. h2 has a high-level API (`acknowledge_received_data`, https://python-hyper.org/projects/h2/en/stable/advanced-usage.html#auto-flow-control) and a low-level API (`increment_flow_control_window`, https://python-hyper.org/projects/h2/en/stable/advanced-usage.html#working-with-flow-control) for managing the flow control window.

> After slightly more thought, probably the return value should be an int, which is how much of data got copied into the buffer. Then if < len(data) I know to block, and I know how much got copied. This makes things simpler than the boolean scheme as you can have an absolute buffer size limit in the stream sender.

In case useful, the way that h2's APIs have approached this is:

> You can find out how much data you can send on a given stream by using the `local_flow_control_window` method, which will do all of these calculations for you. If you attempt to send more than this amount of data on a stream, h2 will throw a `ProtocolError` and refuse to send the data.

Presumably(?) they did it this way because the int retval approach can cause subtle bugs if someone forgets the check, whereas doing `ProtocolError` when someone forgot the check makes the stream data corruption bug fail loudly rather than quietly. (See the mention of `sendall` in https://python-hyper.org/projects/h2/en/stable/advanced-usage.html#sending-data.)

**Comment by gschaffner** [comment]
> I picked a callback here as we don't want the blocked thread to poll, as that introduces latency in it waking up and/or wastes effort polling when progress is still not possible. I considered returning an event too, but that had the same latency issue due to event processing being associated with timers or the send thread typically. Of course, there might be other mechanisms! This is just what I've thought of so far.

FWIW what h2's API does here is give the application a `WindowUpdated` state machine event and let the application do `can_send_event.set()` or whatever to unblock their sender, which is e.g. waiting for `await can_send_event.wait()`.
